---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
data(msleep)
library(infer)
```

```{r}
sleep_data <- janitor::clean_names(msleep)

sleep_data
```

```{r}
sleep_data %>% 
  specify(response = sleep_total) %>% 
  generate(reps = 200, type = "bootstrap") %>% 
  calculate(stat = "mean") %>% 
  get_p_value(obs_stat = 7, direction = "both")
```

```{r}
null_distribution <- sleep_data %>% 
  filter(vore %in% c("omni", "herbi")) %>% 
  specify(sleep_total ~ vore) %>% 
  hypothesise(null = "independence") %>% 
  generate(reps = 10000, type = "permute") %>% 
  calculate(stat = "diff in means", order = c("omni", "herbi"))
```

```{r}
observed_stat <- sleep_data %>% 
  filter(vore %in% c("omni", "herbi")) %>%
  specify(sleep_total ~ vore) %>% 
  calculate(stat = "diff in means", order = c("omni", "herbi"))
```

```{r}
null_distribution %>% 
  visualise(bins = 30) +
  shade_p_value(obs_stat = observed_stat, direction = "right")

null_distribution %>% 
  get_p_value(obs_stat = observed_stat, direction = "right")
```

